name: Node.js CI

on:
  push:
    paths:
     - 'package.json'
     - '.github/workflows/node.js.yml'

jobs:
  publish-npm:

    runs-on: macos-latest

    # 任务的步骤
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - run: pnpm
    - run: pnpm build

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
