name: Node.js CI

on:
  push:
    paths:
     - 'package.json'
     - '.github/workflows/node.js.yml'

jobs:
  publish-npm:
    runs-on: macos-latest

    # 任务的步骤
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - uses: pnpm/action-setup@v2
      with:
        version: 7.5.2

    - run: pnpm i
    - run: pnpm build
    - run: npm publish --access public

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
